### ISSUE TITLE
Reverse terminology

### ISSUE THREAD

**Issue by mglt** [ietf-homenet-wg/ietf-homenet-hna#23] opened 2019-06-06 19:52 UTC
I am wondering if we need that terminology. I would rather bind the different zones to the one we already defined for the forwarding DNS.

**Comment by mcr** [comment] 2020-02-27 18:31
please explain more.  Are you saying that you want the reverse zone to be published as part of the forward, and the pointed to by DNAME or something like that?    I think that we do need to talk more about how the reverse zone is managed, as it has a different relationship to it's parent than the forward zone.

**Comment by mcr** [comment] 2020-02-28 15:30
* Homenet Reverse Zone: The reverse zone file associated with the Public
Homenet Zone.

**Comment by mcr** [comment] 2020-02-28 16:16
Duplicate of #17.

**Closed by mcr** 2020-02-28 16:16 UTC
